version: "3.6"
services:
  notebook:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ocampor/notebook:1.0.0-base
    working_dir: /notebooks
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
